### ISSUE TITLE
关于微信发送图片后崩溃问题的修复

### ISSUE THREAD

**Issue by iamliuzy** [iamliuzhiyu/covid_19_data#1]
# 关于微信发送图片后崩溃问题的修复
我在运行时发现一个问题，在微信选择图片后会崩溃（闪退）
我目前没有解决办法，或许是pyautogui点击速度过快造成的。
希望有人帮忙一起修复这个问题。
如有人发现解决方案，请回复我。

**Comment by iamliuzhiyu** [comment]
> # 关于微信发送图片后崩溃问题的修复
> 我在运行时发现一个问题，在微信选择图片后会崩溃（闪退）
> 我目前没有解决办法，或许是pyautogui点击速度过快造成的。
> 希望有人帮忙一起修复这个问题。
> 如有人发现解决方案，请回复我。

目前我已发布版本1.02测试版，在每一次鼠标、键盘操作后加入一个0.5秒的等待时间。但是还没有进行测试。

**Comment by iamliuzy** [comment]
> > # 关于微信发送图片后崩溃问题的修复
> > 我在运行时发现一个问题，在微信选择图片后会崩溃（闪退）
> > 我目前没有解决办法，或许是pyautogui点击速度过快造成的。
> > 希望有人帮忙一起修复这个问题。
> > 如有人发现解决方案，请回复我。
> 
> 目前我已发布版本1.02测试版，在每一次鼠标、键盘操作后加入一个0.5秒的等待时间。但是还没有进行测试。

目前我已进行测试，软件运行良好，测试成功。后续我会加入更多功能。
